name: "housing"
version: "1.0.0"
config-version: 2

profile: "housing"

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  housing:
    +materialized: view
